### ISSUE TITLE
Server dockerization

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/incubation-dcx#121]
To enable easy local development, it would be ideal to include dockerfiles and a docker-compose file in the server package. The goal is to containerize the whole stack (issuer and applicant servers) as well as a local dwn so users could easily install the server package, run the docker stack and develop locally against that.

**Comment by adalundhe** [comment]
.take

**Comment by adalundhe** [comment]
I'm working on the `.devcontainer` setup over here!

https://github.com/adalundhe/incubation-dcx/tree/AL-add-devcontainer-env

Should have a draft PR up shortly. ❤  Let me know if there's anything additional we'd like in the NodeJS devcontainer - for now it's a relatively complete version of the usual Devcontainer I use for my own projects minus unecessary fluff like the `awscli`. It does include nice things like the `gh` cli, bash completion, etc!

**Comment by blackgirlbytes** [comment]
worddd this is looking good ❤ appreciate you, Ada!!!

**Comment by adalundhe** [comment]
Added a nice README!

https://github.com/adalundhe/incubation-dcx/blob/AL-add-devcontainer-env/docs/LOCAL_DEVELOPMENT.md

**Comment by adalundhe** [comment]
PR is up here!

https://github.com/TBD54566975/incubation-dcx/pull/146

Let me know if there's anything y'all run into in testing or any tweaks y'all would like (preference or otherwise)! I'm happy to do it all! :D

**Comment by blackgirlbytes** [comment]
WHOOOOOOOO! thank you @adalundhe!

**Comment by bnonni** [comment]
Completed by #146
